name: commit_risk_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0
  - scikit-learn=1.1.1
  - pandas>=1.3.0
  - numpy>=1.20.0
  - pip:
    - azureml-defaults>=1.41.0
    - azureml-core>=1.41.0
    - mlflow>=1.26.0
    - azureml-mlflow>=1.41.0
    - inference-schema>=1.3.0
    - onnxruntime>=1.10.0
    - joblib>=1.1.0